plugins {
    id 'java-library'
    id 'io.qameta.allure' version '2.11.2'
    id "io.freefair.lombok" version "8.6"
}

allure {
    report {
        version.set("2.27.0")
    }
    adapter {
        aspectjVersion.set("1.9.22")
        aspectjWeaver.set(true) // @Step weaving
        frameworks {
            junit5 {
                adapterVersion.set("2.27.0")
            }
        }
    }
}

repositories {
    mavenCentral()
}

def restAssuredVersion = "5.4.0",
    jUnitVersion      = "5.10.2",
    assertJVersion    = "3.26.0",
    allureVersion     = "2.27.0",
    jacksonVersion    = "2.17.2",
    slf4jVersion      = "2.0.13",
    httpcoreVersion   = "4.4.16"

dependencies {
    testImplementation(
            "io.rest-assured:rest-assured:${restAssuredVersion}",
            "io.rest-assured:json-schema-validator:${restAssuredVersion}",
            "io.qameta.allure:allure-junit5:${allureVersion}",
            "io.qameta.allure:allure-rest-assured:${allureVersion}",
            "org.junit.jupiter:junit-jupiter:${jUnitVersion}",
            "org.assertj:assertj-core:${assertJVersion}",
            "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}",
            "org.apache.httpcomponents:httpcore:${httpcoreVersion}" // for org.apache.http.HttpStatus
    )
    testRuntimeOnly("org.slf4j:slf4j-simple:${slf4jVersion}")
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
    systemProperty "junit.jupiter.execution.parallel.enabled", "false"
}

compileJava { options.encoding = 'UTF-8' }
compileTestJava { options.encoding = 'UTF-8' }

task API(type: Test) {
    useJUnitPlatform {
        includeTags("Booking", "Auth")
    }
}
